#ifndef MC_CONFIG_H
#define MC_CONFIG_H

#include <stddef.h>
#include <stdint.h>

#define MC_PROTOCOL_VERSION 47
#define MC_DEFAULT_BAUD 921600u
#define MC_DEFAULT_CPU_FREQ_MHZ 72u

#define MC_RX_RING_CAP 8192u
#define MC_TX_RING_CAP 49152u
#define MC_MAX_PACKET_BODY 32768u
#define MC_MAX_USERNAME 16u
#define MC_MAX_STRING_BYTES 32767u

#ifndef MC_PROTOCOL_COMPRESSION_ENABLE
#define MC_PROTOCOL_COMPRESSION_ENABLE 0
#endif

#ifndef MC_COMPRESSION_THRESHOLD
#define MC_COMPRESSION_THRESHOLD 8192u
#endif

#ifndef MC_USE_PSRAM_COMPRESSED_MAP
#define MC_USE_PSRAM_COMPRESSED_MAP 0
#endif

#define MC_TICK_BUDGET_RX_BYTES 512u
#define MC_TICK_BUDGET_TX_BYTES 512u
#define MC_TICK_BUDGET_PACKETS 4u

#define MC_DIMENSION_OVERWORLD 0
#define MC_ENTITY_ID_SELF 1
#ifndef MC_SERVER_TICKS_PER_SECOND
#define MC_SERVER_TICKS_PER_SECOND (MC_DEFAULT_CPU_FREQ_MHZ * 1000000u)
#endif
#ifndef MC_KEEPALIVE_INTERVAL_TICKS
#define MC_KEEPALIVE_INTERVAL_TICKS (MC_SERVER_TICKS_PER_SECOND * 10u)
#endif

#if MC_PROTOCOL_COMPRESSION_ENABLE != 0 && MC_PROTOCOL_COMPRESSION_ENABLE != 1
#error "MC_PROTOCOL_COMPRESSION_ENABLE must be 0 or 1"
#endif

#if MC_USE_PSRAM_COMPRESSED_MAP != 0 && MC_USE_PSRAM_COMPRESSED_MAP != 1
#error "MC_USE_PSRAM_COMPRESSED_MAP must be 0 or 1"
#endif

#if MC_COMPRESSION_THRESHOLD <= 0
#error "MC_COMPRESSION_THRESHOLD must be positive"
#endif

#if MC_SERVER_TICKS_PER_SECOND <= 0
#error "MC_SERVER_TICKS_PER_SECOND must be positive"
#endif

#if MC_KEEPALIVE_INTERVAL_TICKS <= 0
#error "MC_KEEPALIVE_INTERVAL_TICKS must be positive"
#endif

#if MC_USE_PSRAM_COMPRESSED_MAP && !MC_PROTOCOL_COMPRESSION_ENABLE
#error "MC_USE_PSRAM_COMPRESSED_MAP requires MC_PROTOCOL_COMPRESSION_ENABLE"
#endif

#endif
