#include "mc_config.h"
#include "mc_firmware_config.h"
#include "mc_link.h"

#define ASSERT_TRUE(expr) do { if (!(expr)) return 1; } while (0)
#define ASSERT_EQ(a, b) do { if ((a) != (b)) return 1; } while (0)

int test_firmware_config(void)
{
    ASSERT_EQ(MC_UART_ID_0, 0u);
    ASSERT_EQ(MC_UART_ID_1, 1u);
    ASSERT_EQ(MC_UART0_BAUD, 115200u);
    ASSERT_EQ(MC_UART1_BAUD, 115200u);
    ASSERT_EQ(MC_BRIDGE_UART_ID, MC_UART_ID_0);
    ASSERT_EQ(MC_LOG_UART_ID, MC_UART_ID_1);
    ASSERT_EQ(MC_BRIDGE_UART_BAUD, 115200u);
    ASSERT_EQ(MC_LOG_UART_BAUD, 115200u);
    ASSERT_EQ(MC_LOG_LEVEL, MC_LOG_INFO);
    ASSERT_EQ(MC_M2C_AGGRESSIVE_TX, 0);
    ASSERT_EQ(MC_UART0_TX_PACE_LOOPS, 781u);
    ASSERT_EQ(MC_UART0_WRITE_BURST_BYTES, 128u);
    ASSERT_EQ(MC_LINK_TX_MAX_BYTES_PER_LOOP, MC_TICK_BUDGET_TX_BYTES);
    ASSERT_EQ(MC_LINK_TX_PENDING_BYTES, MC_TICK_BUDGET_TX_BYTES);
    ASSERT_TRUE(MC_LINK_TX_PENDING_BYTES >= MC_LINK_TX_MAX_BYTES_PER_LOOP);
    ASSERT_TRUE(MC_LINK_TX_PENDING_BYTES >= MC_LINK_MAX_ENCODED_LEN);
    ASSERT_TRUE(MC_LINK_TX_MAX_BYTES_PER_LOOP == MC_TICK_BUDGET_TX_BYTES);
    ASSERT_EQ(MC_PROTOCOL_COMPRESSION_ENABLE, 0);
    ASSERT_EQ(MC_COMPRESSION_THRESHOLD, 8192u);
    ASSERT_EQ(MC_USE_PSRAM_COMPRESSED_MAP, 0);
    ASSERT_TRUE(MC_BRIDGE_UART_BAUD >= 115200u);
    ASSERT_EQ(MC_TRACE_LINK_UART_RX_DATA, 0);
    ASSERT_EQ(MC_LOG_LINK_UART_IO, 0);
    return 0;
}
